### ISSUE TITLE
React native encode base64

### ISSUE THREAD

**Issue by fahadhaq** [mathiasbynens/base64#11]
Hi, Just trying to run your example from the readme to see if the code works correctly. 

```
import utf8 from 'utf8'
import base64 from 'base-64'

var text = 'foo © bar 𝌆 baz';
var bytes = utf8.encode(text);
var encoded = base64.encode(bytes);
console.log(encoded);
// → 'Zm9vIMKpIGJhciDwnYyGIGJheg=='

```
When I run the above code I am getting the following. Can you please let me know what I am doing wrong please.

W29iamVjdCBBcnJheUJ1ZmZlcl0=

Please help

**Comment by mathiasbynens** [comment]
That’s the Base64-encoding of the string `"[object ArrayBuffer]"`.

**Comment by mathiasbynens** [comment]
It doesn’t look like you’re using the same “utf8.js” as here: https://github.com/mathiasbynens/base64#base64encodeinput

**Comment by adamivancza** [comment]
Yeah actually I had the same problem in React Native. I tried with all versions of utf8 package but none of them seemed to work. However I was able to make it work using this: https://stackoverflow.com/a/42334410/851490

**Comment by mathiasbynens** [comment]
https://github.com/facebook/react-native/pull/17146

**Comment by adamivancza** [comment]
Awesome @mathiasbynens - thanks for the update on this!
