### ISSUE TITLE
RangeError: Maximum call stack size exceeded for large ArrayBuffer

### ISSUE THREAD

**Issue by dahudson88** [mathiasbynens/base64#13]
Hello,

I am running into the following error:
RangeError: Maximum call stack size exceeded.
I am converting an ArrayBuffer to a Base64String using the encoding function.

I am getting this ArrayBuffer as a response from a server.  The ArrayBuffer length is 92778.  I am thinking that this is causing the problem.  Could someone confirm that this may cause this error?  And if there is a workaround that may be able to help.

Below is the code that I am running to generate the string
```
var base64 = require('base-64');
var pdf_base64Str = base64.encode(String.fromCharCode.apply(null, new Uint8Array(response.data)));
```

Thanks

**Comment by mathiasbynens** [comment]
I suspect this is not a base-64 bug.

Is this enough to reproduce the issue?

```js
String.fromCharCode.apply(null, new Uint8Array(response.data));
```

To work around the problem you could batch the calls to `String.fromCharCode`. Don’t call it just once, but call it once for every 1024 entries, for example, and them concatenate the resulting strings.

**Comment by dahudson88** [comment]
Thanks so much.  that did the trick
