### ISSUE TITLE
Not working with UTF-8

### ISSUE THREAD

**Issue by kukko** [mathiasbynens/base64#14]
I tried to convert a JSON string to Base64 with this package, depend on the README, but it's simply return an [object ArrayBuffer] and I can't get the value from the object as a string.

Here is the code which I have written.
```
var text = data.profile; // It is a JSON string.
var bytes = utf8.encode(text);
var encoded = base64.encode(bytes);
_this.changeURL(_this.domain+"user/fb_login_callback?userNode="+encoded);
```

**Comment by mathiasbynens** [comment]
This doesn’t look like a bug in this library.

If you want help, please show your full code example.
