### ISSUE TITLE
Convert Base64 string to Utf-8 byte array

### ISSUE THREAD

**Issue by liveyourheart** [mathiasbynens/base64#15]
I'm currently working on a feature to provide images to a partner in utf-8 bytecode.  We currently store images as base64 strings.  I've tried using your base64 and utf8 packages to accomplish this, but I think I'm doing something wrong.

My thought process is:
1. decode string from base 64
2. encode as utf-8
3. create a buffer from the utf string
4. spread the buffer to an array.

````
// const b64 = base64 string
const bytes = base64.decode(b64);
const utf = utf8.encode(bytes);

const buff = Buffer.from(utf, 'utf8');
const arr = [...buff];
````

**Comment by mathiasbynens** [comment]
The README shows how to deal with UTF-8: https://github.com/mathiasbynens/base64#base64decodeinput
