### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by daniel-shuy** [mathiasbynens/base64#24]
Please create a new release, the current release in NPM has the license in the wrong place, which is causing it to be detected as `License: none`, and is already fixed in https://github.com/mathiasbynens/base64/commit/c605dea00939422cdd427e84e7d5ad4257badb60#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R15

**Comment by mathiasbynens** [comment]
Done: v1.0.0

**Comment by daniel-shuy** [comment]
Thank you!
