### ISSUE TITLE
How do i import this

### ISSUE THREAD

**Issue by Brian-Kaplan** [mathiasbynens/base64#5]
I can't use require('blah') only import.

What is the correct syntax to import this.

**Comment by mathiasbynens** [comment]
Which environment are you targeting? Are you using Babel to transpile? How are you importing your other libraries?

**Comment by iiitmahesh** [comment]
I am using react-native. please let me know how to import this??

@Brian-Kaplan  have you solved this?

**Comment by mathiasbynens** [comment]
Closing since I never got a response to my follow-up question.
