### ISSUE TITLE
Returns error if string I want to decode contains dot character (.)

### ISSUE THREAD

**Issue by kunokdev** [mathiasbynens/base64#6]
If string contains `.` while calling `decode` method,  then next error will appear:

> InvalidCharacterError
>     at /home/kuno/code/aviokarte-web/node_modules/base-64/base64.js:23:36
>     at Object.<anonymous> (/home/kuno/code/aviokarte-web/node_modules/base-64/base64.js:165:2)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.require (module.js:497:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/home/kuno/code/aviokarte-web/seeders/fetch_sample_pages.js:3:14)
>

**Comment by mathiasbynens** [comment]
This is intended behavior. `.` is not in the Base64 alphabet. https://github.com/mathiasbynens/base64#base64decodeinput
